### ISSUE TITLE
Remove the 'intercom' dependency for AMD/require.js

### ISSUE THREAD

**Issue by mdedetrich** [gdi2290/angular-intercom#24]
We are using require.js on our end, and there seems to be a dependency which shouldn't even exist. Specifically this area

https://github.com/gdi2290/angular-intercom/blob/master/angular-intercom.js#L8-L16

The 'intercom' dependency defined in AMD makes no sense, especially if you are using
```javascript
    $intercomProvider
      .asyncLoading(true)
```

When we manually edited the loader to remove this dependency, `angular-intercom` worked fine.

It should be removed, and if someone wants to provide the `intercom` library through AMD/require.js, they can explicitly state it as a dependency (and `angular-intercom` can then detect it in this case)

**Comment by gdi2290** [comment]
could you make a pull request? you wouldn't use `asyncLoading` with requirejs it's only meant for people making simple apps that don't want to include intercom  but that wasn't documented

**Comment by mdedetrich** [comment]
Pull request made, also updated documentation and did some internal testing for both versions (one when using require.js with asyncLoading, the other when specifying the intercom dependency in paths)

**Comment by gdi2290** [comment]
thanks! fixed via https://github.com/gdi2290/angular-intercom/issues/24
