### ISSUE TITLE
$intercom.shutdown() does not reset _options, causing Acquire to not work

### ISSUE THREAD

**Issue by yjwong** [gdi2290/angular-intercom#27]
Hi there,

I currently have Intercom Acquire (so I can use Intercom without users being logged in) and I'm integrating this library into my Angular app.

On load, my app does something like:

```javascript
$intercom.boot({});
```

This is when no user is logged in yet. When a user logs in, my app does something like:

```javascript
$intercom.shutdown();
$intercom.boot(myUser);
```

And finally, then the user logs out, my app does something like:

```javascript
$intercom.shutdown();
$intercom.boot({});
```

Since the `_options` object was never reconstructed after calling `shutdown()`, it still contains the details of the user (`myUser`) when `$intercom.boot({})` is called. 

Adding this code snippet after `global.Intercom('shutdown')` fixes the problem:

```javascript
_options = {};

// ensure appID is added to _options
if (config.appID) {
    _options.app_id = _options.app_id || config.appID;
}
angular.extend(_options, IntercomSettings);
```

I'd submit a pull request, but I'm not sure how you'd want to produce the minified file.

**Comment by gdi2290** [comment]
make a pull request then I'll update the minified version

**Comment by gdi2290** [comment]
I added you and @niemyjski to the repo

**Comment by niemyjski** [comment]
Thanks!

**Comment by yjwong** [comment]
Thanks! By any chance, could you do a new release on Bower?

**Comment by gdi2290** [comment]
you can tag a new version and push it up so bower an pick it up
