### ISSUE TITLE
Bower installation doesn't contain angular-intercom.js

### ISSUE THREAD

**Issue by mbiermann** [gdi2290/angular-intercom#29]
I've added the dependency `"angular-intercom": "^2.1.1"` to my bower.json and hit `bower install` in the console. That installed the lib but when I check what bower_components contains afterwards, I only find the files in the attached screenshot, but not the most important `angular-intercom.js`. Does somebody have this issue or ideas what could cause it?
![image](https://cloud.githubusercontent.com/assets/2660075/12681766/867d296a-c6b0-11e5-80d7-8a5a65a2ec9a.png)

**Comment by yjwong** [comment]
Hmm... I just did a quick check on a clean directory, it seems I do have `angular-intercom.js` and `angular-intercom.min.js`. Did you try removing `bower_components/angular-intercom` and installing again?

**Comment by niemyjski** [comment]
closing this until we get a response or a second repo.

**Comment by gdi2290** [comment]
I don't see this could happen. Bower work on git tags and there was a tag released that includes the files
