### ISSUE TITLE
The example in the project description isn't available

### ISSUE THREAD

**Issue by eedeebee** [gdi2290/angular-intercom#32]
This URL `https://gdi2290.net/angular-intercom/example/` is a no go for me. Chrome says:

```
gdi2290.net’s server DNS address could not be found
```

**Comment by Goddak** [comment]
I second this one, I found your .com address and tried to visit ```/angular-intercom/example/``` but that doesn't work so I'm guessing it wasn't moved over. It would be handy to have an example, it would also be handle to have a method list detailing the exposed methods for reference.

**Comment by PatrickJS** [comment]
thanks, I removed the link
